# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:49:19+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class GetcurrencyrateGetResponse(BaseModel):
    Code: Optional[str] = None
    Country: Optional[str] = None
    Credits: Optional[str] = None
    Name: Optional[str] = None
    Rate: Optional[str] = None
    Symbol: Optional[str] = None
